#!/bin/bash

function assureDirExists {
	if [[ ! -d $1 ]]; then
		SAVEIFS=$IFS
		IFS=
		mkdir -m 755 $1
		IFS=$SAVEIFS
		return 0
	else
		return 1
	fi
}

if [[ $# < 1 ]]; then
	echo "No option is given" > /dev/stderr
	exit 1;
fi

if [[ -f $1 ]]; then
	return 1
else
	return 0
fi