#!/bin/bash

function assureDirExists {
	if [[ ! -d $1 ]]; then
		SAVEIFS=$IFS
		IFS=
		mkdir -m 755 $1
		IFS=$SAVEIFS
		return 0
	else
		return 1
	fi
}

if [[ $# < 1 ]]; then
	echo "No option is given" > /dev/stderr
	exit 1
fi

if [[ $1 == create ]]; then
	if [ $# -gt 3 ] || [ $# -lt 2 ]; then
		echo "The wrong number of arguments are given to an option (too few 
			or too many)" > /dev/stderr
		exit 1
	fi
	if [[ $2 = */* ]]; then
		echo "Invalid arguments: ""$2" > /dev/stderr
		exit 1
	fi
	if [[ -f /home/ytl264/.question/questions/$2 ]]; then
		echo "The question name exists already" > /dev/stderr
		exit 1
	fi
	if [[ $# > 2 ]]; then
		content=$(echo $3)
	else
		echo "please enter the question:"
		read content
	fi
	if [[ $content = *====* ]]; then
		echo "not added! question contains \"====\"" > /dev/stderr
		exit 1
	fi
	if [[ $content = "" ]]; then
		echo "not added! empty question" > /dev/stderr
		exit 1
	fi
	assureDirExists "/home/ytl264/.question"
	assureDirExists "/home/ytl264/.question/questions"
	touch "/home/ytl264/.question/questions/$2"
	chmod 705 "/home/ytl264/.question/questions/$2"
	echo $content >> "/home/ytl264/.question/questions/$2"
	exit 0
fi

if [[ $1 == answer ]]; then
	if [ $# -gt 4 ] || [ $# -lt 3 ]; then
		echo "The wrong number of arguments are given to an option (too few 
			or too many)" > /dev/stderr
		exit 1
	fi
	if [[ ! $2 = */* ]]; then
		echo "Invalid arguments: ""$2" > /dev/stderr
		exit 1
	fi
	user=$(echo $2 | cut -d/ -f1)
	qname=$(echo $2 | cut -d/ -f2)
	if [[ ! (-f "/home/$user/.question/questions/$qname") ]]; then
		echo "No such question: "$user"/"$qname > /dev/stderr
		exit 1
	fi
	if [[ $3 = */* ]]; then
		echo "Invalid arguments: ""$3" > /dev/stderr
		exit 1
	fi
	if [[ -f /home/ytl264/.question/answers/$user/$qname/$3 ]]; then
		echo "The answer name exists already" > /dev/stderr
		exit 1
	fi
	if [[ $# > 3 ]]; then
		content=$(echo $4)
	else
		echo "please enter the answer:"
		read content
	fi
	if [[ $content = *====* ]]; then
		echo "not added! the answer contains \"====\"" > /dev/stderr
		exit 1
	fi
	if [[ $content = "" ]]; then
		echo "not added! empty answer" > /dev/stderr
		exit 1
	fi
	assureDirExists "/home/ytl264/.question"
	assureDirExists "/home/ytl264/.question/answers"
	assureDirExists "/home/ytl264/.question/answers/$user"
	assureDirExists "/home/ytl264/.question/answers/$user/$qname"
	SAVEIFS=$IFS
	IFS=
	touch "/home/ytl264/.question/answers/$user/$qname/$3"
	chmod 705 "/home/ytl264/.question/answers/$user/$qname/$3"
	echo $content >> "/home/ytl264/.question/answers/$user/$qname/$3"
	IFS=SAVEIFS
	exit 0
fi

if [[ $1 == list ]]; then
	if [ $# -gt 2 ] || [ $# -lt 1 ]; then
		echo "The wrong number of arguments are given to an option (too few 
			or too many)" > /dev/stderr
		exit 1
	fi
	if [[ ! $2 == "" ]]; then
		if [[ $2 = */* ]]; then
			echo "Invalid arguments: ""$2" > /dev/stderr
			exit 1
		fi
		if [[ ! (-d "/home/$2/.question") ]]; then
			#echo "No such user" > /dev/stderr
			#exit 1
			exit 0
		else
			ls "/home/$2/.question/questions" | sed "s/^/$2\//"
		fi
	else
		while read line; do
			ls "/home/$line/.question/questions" | sed "s/^/$line\//"
		done < "/home/unixtool/data/question/users"
	fi
	exit 0
fi

if [[ $1 == vote ]]; then
	if [ $# -gt 4 ] || [ $# -lt 3 ]; then
		echo "The wrong number of arguments are given to an option (too few 
			or too many)" > /dev/stderr
		exit 1
	fi
	if [[ !($2 = up || $2 = down) ]]; then
		echo "Invalid arguments: ""$2" > /dev/stderr
		exit 1
	fi
	if [[ ! $3 = */* ]]; then
		echo "Invalid arguments: ""$3" > /dev/stderr
		exit 1
	fi
	user=$(echo $3 | cut -d/ -f1)
	qname=$(echo $3 | cut -d/ -f2)
	if [[ ! (-f "/home/$user/.question/questions/$qname") ]]; then
		echo "No such question exists" > /dev/stderr
		exit 1
	fi
	if [[ $4 == "" ]]; then
		assureDirExists "/home/ytl264/.question"
		assureDirExists "/home/ytl264/.question/votes"
		assureDirExists "/home/ytl264/.question/votes/$user"
		touch "/home/ytl264/.question/votes/$user/$qname"
		chmod 705 "/home/ytl264/.question/votes/$user/$qname"
		sed -i -e "/^up$/d" "/home/ytl264/.question/votes/$user/$qname"
		sed -i -e "/^down$/d" "/home/ytl264/.question/votes/$user/$qname"
		echo $2 >> "/home/ytl264/.question/votes/$user/$qname"
	else
		if [[ ! $4 = */* ]]; then
			echo "Invalid arguments: ""$4" > /dev/stderr
			exit 1
		fi
		auser=$(echo $4 | cut -d/ -f1)
		aname=$(echo $4 | cut -d/ -f2)
		if [[ ! -f "/home/$auser/.question/answers/$user/$qname/$aname" ]]; then
			echo "The answer does note exist" > /dev/stderr
			exit 1
		fi
		assureDirExists "/home/ytl264/.question"
		assureDirExists "/home/ytl264/.question/votes"
		assureDirExists "/home/ytl264/.question/votes/$user"
		touch "/home/ytl264/.question/votes/$user/$qname"
		chmod 705 "/home/ytl264/.question/votes/$user/$qname"
		sed -i -e "/up $auser\/$aname/d" "/home/ytl264/.question/votes/$user/$qname"
		sed -i -e "/down $auser\/$aname/d" "/home/ytl264/.question/votes/$user/$qname"
		echo $2" "$auser"/"$aname >> "/home/ytl264/.question/votes/$user/$qname"
	fi
	exit 0
fi

if [[ $1 == view ]]; then
	if [ $# -lt 2 ]; then
		echo "The wrong number of arguments are given to an option (too few 
			or too many)" > /dev/stderr
		exit 1
	fi
	for file in "$@"; do
		if [[ $file == view ]]; then
			continue
		fi
		user=$(echo $file | cut -d/ -f1)
		qname=$(echo $file | cut -d/ -f2)
		if [[ ! (-f "/home/$user/.question/questions/$qname") ]]; then
			echo "No such question id exists: ""$file" > /dev/stderr
			exit 1
		else
			count=0
			while read usr; do
				if [[ -f "/home/$usr/.question/votes/$user/$qname" ]]; then
					echo "/home/$usr/.question/votes/$user/$qname"
					vote=$(grep "^\(up\|down\)\s*$" "/home/$usr/.question/votes/$user/$qname" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tail -1)
					echo $vote
					if [[ $vote == up ]]; then
						count=$((count+1))
						echo $count
					elif [[ $vote == down ]]; then				
						count=$((count-1))
						echo $count
					fi
				 	#count=$((count+$(sed -n -e "/^up\s*$/p" "/home/$usr/.question/votes/$user/$qname" | wc -l)))
				 	#count=$((count-$(sed -n -e "/^down\s*$/p" "/home/$usr/.question/votes/$user/$qname" | wc -l)))
				fi
			done < /home/unixtool/data/question/users
			echo $count" "$user"/"$qname
			cat "/home/$user/.question/questions/$qname"
			echo "===="
            
			while read usr; do
				if [[ -d "/home/$usr/.question/answers/$user/$qname" ]]; then
					SAVEIFS=$IFS
					IFS=$(echo -en "\n\b")
					for ans in $(ls "/home/$usr/.question/answers/$user/$qname"); do
						count=0
						while read u; do
							if [[ -f "/home/$u/.question/votes/$user/$qname" ]]; then							
						 		count=$((count+$(sed -n -e "/up $usr\/$ans/p" "/home/$u/.question/votes/$user/$qname" | wc -l)))
						 		count=$((count-$(sed -n -e "/down $usr\/$ans/p" "/home/$u/.question/votes/$user/$qname" | wc -l)))
							fi
						done < /home/unixtool/data/question/users
						echo $count" "$usr"/"$ans" @"$user"/"$qname
						cat "/home/$usr/.question/answers/$user/$qname/$ans"
						echo "===="
					done
					IFS=$SAVEIFS
				fi
			done < /home/unixtool/data/question/users
		    
        fi
	done
	exit 0
fi

echo "No such option exists" > /dev/stderr
exit 1

	

	
	
